# Generated by Django 4.0.4 on 2022-05-14 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokesite', '0003_alter_characters_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='rating',
            field=models.PositiveIntegerField(default=19, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
