# Generated by Django 4.0.4 on 2022-05-14 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokesite', '0004_alter_characters_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='rating',
        ),
        migrations.AddField(
            model_name='characters',
            name='level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='characters',
            name='pokedex',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='characters',
            name='pokemons',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
